[project]
name = "base-telegram"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.1",
    "djangorestframework>=3.16.0",
    "pydantic>=2.11.4",
    "pysocks>=1.7.1",
    "requests>=2.32.3",
]
